clone:
  depth: 1
pipelines:
  default:
    - step:
        image:
          name: golang:latest
        script:
          - git submodule update --init
          - mkdir -p out

          - apt-get update
          - apt-get install -y checkinstall upx

          - env GOOS=linux GOARCH=amd64 make
          - make compress
          - mv tk-ssh-agent out/tk-ssh-agent-x86_64-linux

          - env GOOS=darwin GOARCH=amd64 make
          - make compress
          - mv tk-ssh-agent out/tk-ssh-agent-x86_64-darwin

          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/trustedkey/tk-ssh-agent/downloads" --form files=@"./out/tk-ssh-agent-x86_64-linux"
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/trustedkey/tk-ssh-agent/downloads" --form files=@"./out/tk-ssh-agent-x86_64-darwin"
